on: 
  schedule: 
    - cron: "*/60 * * * *"
    
  workflow_dispatch:
  
name: trafic

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 

    steps:
      # imports an action from another repository, 
      # that enables the machine
      # to access the code inside our repository
      - uses: actions/checkout@v3 
      # imports an action from another repository, 
      # that installs R on the machine
      - uses: r-lib/actions/setup-r@v2
        with:
          # uses the RStudio Package Manager
          use-public-rspm: true

        
      # imports an action from another repository, 
      # that deals with the dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          # here we have to add all the packages we used in the script!
          packages: |
            any::sf
            any::hereR
            any::here
            any::tibble
          HERE: $${{ var.HERE }}

      - name: See envs
        run: |
          env
          
      - name: Execute Script
        run: |
          Rscript "main.R"           

      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main
        env: 
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

